config/routes.rb
WdiImdb::Application.routes.draw do

  resources :characters do
    collection do
      match 'search' => 'characters#search', :via => [:get, :post], :as => :search
    end
  end
  resources :castings
  resources :actors do
    collection do
      match 'search' => 'actors#search', :via => [:get, :post], :as => :search
    end
  end
  resources :movies do
    collection do
      match 'search' => 'movies#search', :via => [:get, :post], :as => :search
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :castings
  has_many :movies, through: :castings
  has_many :characters, through: :castings

  attr_accessible :age, :nick_name, :name, :movie_id, :character_id, :actor_image

  mount_uploader :actor_image, ActorImageUploader
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    load_and_authorize_resource
  # GET /actors
  # GET /actors.json
  def index
    @q = Actor.search(params[:q])
    @actors = @q.result(:distinct => true)
  end


  def search
    index
    render :index
  end
  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :nick_name %><br />
    <%= f.text_field :nick_name %>
  </div>
   <div class="field">
    <%= f.label :actor_image %><br />
    <%= f.file_field :actor_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/_search.html.erb
<div class="search">
 <%= search_form_for @q, url: search_actors_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Actor Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_movies_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Movie Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_characters_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Character Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Listing actors</h1>
<%= render 'search' %>
<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Age</th>
    <th>Alias</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @actors.each do |actor| %>
  <tr>
    <td><%= image_tag actor.actor_image.thumb.url %></td>
    <td><%= link_to actor.name, actor_path(actor)%></td>
    <td><%= actor.age %></td>
    <td><%= actor.nick_name %></td>
    <% if can? :create, Character %>
    <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
    <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @actor.name %>
</p>

<p>
  <%= image_tag @actor.actor_image.detail.url %>
</p>


<p>
  <b>Age:</b>
  <%= @actor.age %>
</p>

<p>
  <b>Nick-name:</b>
  <%= @actor.nick_name %>
</p>

<p>
  <b>Movies:</b>
  <% @actor.movies.each do |movie| %>
  <%= link_to movie.name, movie_path(movie) %>
  <% end %>
  <br>
</p>

<p>
  <b>Characters:</b>
  <% @actor.characters.each do |character| %>
  <%= link_to character.name, character_path(character) %>
  <% end %>
  <br>
</p>

<% if can? :create, Actor%>
<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>
<% end %>