config/routes.rb
WdiImdb::Application.routes.draw do

  resources :characters do
    collection do
      match 'search' => 'characters#search', :via => [:get, :post], :as => :search
    end
  end
  resources :castings
  resources :actors do
    collection do
      match 'search' => 'actors#search', :via => [:get, :post], :as => :search
    end
  end
  resources :movies do
    collection do
      match 'search' => 'movies#search', :via => [:get, :post], :as => :search
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    load_and_authorize_resource
  # GET /movies
  # GET /movies.json
  def index
     @q = Movie.search(params[:q])
    @movies = @q.result(:distinct => true)
  end

  def search
    index
    render :index
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :run_time %><br />
    <%= f.text_field :run_time %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :movie_image %><br />
    <%= f.file_field :movie_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_search.html.erb
<div class="search">
 <%= search_form_for @q, url: search_actors_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Actor Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_movies_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Movie Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_characters_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Character Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>
<%= render 'search' %>
<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Rating</th>
    <th>Year</th>
    <th>Run time</th>
    <th>Director</th>

    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= image_tag movie.movie_image.thumb.url %></td>
    <td><%= link_to movie.name, movie_path(movie)%></td>
    <td><%= movie.rating %></td>
    <td><%= movie.year %></td>
    <td><%= movie.run_time %></td>
    <td><%= movie.director %></td>
    <% if can? :create, Movie%>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <%= image_tag @movie.movie_image.detail.url %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Run time:</b>
  <%= @movie.run_time %>
</p>

<p>
  <b>Director:</b>
  <%= @movie.director %>
</p>

<p>
  <b>Actors:</b>
  <% @movie.actors.each do |actor| %>
  <%= link_to actor.name, actor_path(actor) %> -
  <% end %>
  <br>
</p>

<p>
  <b>Characters:</b>
  <% @movie.characters.each do |character| %>
  <%= link_to character.name, character_path(character) %>
  <% end %>
  <br>
</p>

<% if can? :create, Actor%>
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<% end %>