config/routes.rb
WdiImdb::Application.routes.draw do

  resources :characters do
    collection do
      match 'search' => 'characters#search', :via => [:get, :post], :as => :search
    end
  end
  resources :castings
  resources :actors do
    collection do
      match 'search' => 'actors#search', :via => [:get, :post], :as => :search
    end
  end
  resources :movies do
    collection do
      match 'search' => 'movies#search', :via => [:get, :post], :as => :search
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/models/casting.rb
class Casting < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie
  belongs_to :character

  attr_accessible :actor_id, :character_id, :movie_id
end

app/controllers/castings_controller.rb
class CastingsController < ApplicationController
  load_and_authorize_resource
  # GET /castings
  # GET /castings.json
  def index
    @castings = Casting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @castings }
    end
  end

  # GET /castings/1
  # GET /castings/1.json
  def show
    @casting = Casting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @casting }
    end
  end

  # GET /castings/new
  # GET /castings/new.json
  def new
    @casting = Casting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @casting }
    end
  end

  # GET /castings/1/edit
  def edit
    @casting = Casting.find(params[:id])
  end

  # POST /castings
  # POST /castings.json
  def create
    @casting = Casting.new(params[:casting])

    respond_to do |format|
      if @casting.save
        format.html { redirect_to @casting, notice: 'Casting was successfully created.' }
        format.json { render json: @casting, status: :created, location: @casting }
      else
        format.html { render action: "new" }
        format.json { render json: @casting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /castings/1
  # PUT /castings/1.json
  def update
    @casting = Casting.find(params[:id])

    respond_to do |format|
      if @casting.update_attributes(params[:casting])
        format.html { redirect_to @casting, notice: 'Casting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @casting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castings/1
  # DELETE /castings/1.json
  def destroy
    @casting = Casting.find(params[:id])
    @casting.destroy

    respond_to do |format|
      format.html { redirect_to castings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/castings_helper.rb
module CastingsHelper
end

app/views/castings/_form.html.erb
<%= form_for(@casting) do |f| %>
  <% if @casting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casting.errors.count, "error") %> prohibited this casting from being saved:</h2>

      <ul>
      <% @casting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br />
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :actor_id %><br />
    <%= f.number_field :actor_id %>
  </div>
  <div class="field">
    <%= f.label :character_id %><br />
    <%= f.number_field :character_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/castings/_search.html.erb
<div class="search">
 <%= search_form_for @q, url: search_actors_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Actor Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_movies_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Movie Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_characters_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Character Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>

app/views/castings/edit.html.erb
<h1>Editing casting</h1>

<%= render 'form' %>

<%= link_to 'Show', @casting %> |
<%= link_to 'Back', castings_path %>

app/views/castings/index.html.erb
<h1>Listing castings</h1>

<table>
  <tr>
    <th>Movie</th>
    <th>Actor</th>
    <th>Character</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @castings.each do |casting| %>
  <tr>
    <td><%= casting.movie_id %></td>
    <td><%= casting.actor_id %></td>
    <td><%= casting.character_id %></td>
    <td><%= link_to 'Show', casting %></td>
    <td><%= link_to 'Edit', edit_casting_path(casting) %></td>
    <td><%= link_to 'Destroy', casting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Casting', new_casting_path %>

app/views/castings/new.html.erb
<h1>New casting</h1>

<%= render 'form' %>

<%= link_to 'Back', castings_path %>

app/views/castings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @casting.movie_id %>
</p>

<p>
  <b>Actor:</b>
  <%= @casting.actor_id %>
</p>

<p>
  <b>Character:</b>
  <%= @casting.character_id %>
</p>


<%= link_to 'Edit', edit_casting_path(@casting) %> |
<%= link_to 'Back', castings_path %>