config/routes.rb
WdiImdb::Application.routes.draw do

  resources :characters do
    collection do
      match 'search' => 'characters#search', :via => [:get, :post], :as => :search
    end
  end
  resources :castings
  resources :actors do
    collection do
      match 'search' => 'actors#search', :via => [:get, :post], :as => :search
    end
  end
  resources :movies do
    collection do
      match 'search' => 'movies#search', :via => [:get, :post], :as => :search
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
has_many :castings
has_many :actors, through: :castings
has_many :movies, through: :castings

  attr_accessible :age, :description, :gender, :name, :actor_id, :movie_id, :character_image

  mount_uploader :character_image, CharacterImageUploader
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  load_and_authorize_resource
  # GET /characters
  # GET /characters.json
  def index
    @q = Character.search(params[:q])
    @characters = @q.result(:distinct => true)
  end

  def search
      index
      render :index
  end
  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br />
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <br />
  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <br />
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <br />
   <div class="field">
    <%= f.label :character_image %>
    <%= f.file_field :character_image %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/_search.html.erb
<div class="search">
 <%= search_form_for @q, url: search_actors_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Actor Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_movies_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Movie Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>
<div class="search">
 <%= search_form_for @q, url: search_characters_path, html: {method: :post}  do |f| %>
      <p><%= f.label :name_start, 'Character Search:' %><%= f.text_field :name_start %>   <%= f.submit %></p>
  <% end %>
</div>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>
<%= render 'search' %>
<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Description</th>

  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= image_tag character.character_image.thumb.url %></td>
    <td><%= link_to character.name, character_path(character)%></td>
    <td><%= character.gender %></td>
    <td><%= character.age %></td>
    <td><%= character.description %></td>
    <% if can? :create, Character %>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />
<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <%= image_tag @character.character_image.detail.url %>
</p>

<p>
  <b>Gender:</b>
  <%= @character.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @character.age %>
</p>

<p>
  <b>Description:</b>
  <%= @character.description %>
</p>

<p>
  <b>Actors:</b>
  <% @character.actors.each do |actor| %>
  <%= link_to actor.name, actor_path(actor) %> -
  <% end %>
  <br>
</p>

<p>
  <b>Movies:</b>
  <% @character.movies.each do |movie| %>
  <%= link_to movie.name, movie_path(movie) %>
  <% end %>
  <br>
</p>

<% if can? :create, Actor%>
<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>
<% end %>